apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello


---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
  - name: http-web
    port: 80
    targetPort: 8080

  selector:
    app: hello

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello
spec:
  hosts:
  - "hello"
  - "hello.dev1"
  - "hello.dev1.svc"
  - "hello.dev1.svc.cluster"
  - "hello.dev1.svc.cluster.local"
    
  http:
  - route:
    - destination:
        host: hello
        subset: v1
      weight: 99
    - destination:
        host: hello
        subset: v2
      weight: 1


---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello
spec:
  host: hello
  subsets:
  - name: v1
    labels:
      version: v1
      app: hello
  - name: v2
    labels:
      version: v2
      app: hello

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: v1
  template:
    metadata:
      labels:
        app: hello
        version: v1
    spec:
      serviceAccountName: hello
      containers:
      - image: docker.io/sekhrivijay/hello-world-flask:latest
        imagePullPolicy: Always
        name: hello-http1
        env:
        - name: PORT
          value: "8080"
        - name: HTTPS
          value: "False"
        - name: VERSION
          value: v1
        ports:
        - containerPort: 8080
          name: http-web


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: v2
  template:
    metadata:
      labels:
        app: hello
        version: v2
    spec:
      serviceAccountName: hello
      containers:
      - image: docker.io/sekhrivijay/hello-world-flask:latest
        imagePullPolicy: Always
        name: hello-http2
        env:
        - name: PORT
          value: "8080"
        - name: HTTPS
          value: "False"
        - name: VERSION
          value: v2
        ports:
        - containerPort: 8080
          name: http-web




